### PR TITLE
Improve Performance of now-u website

### LINKED ISSUE #52: Investigate and Improve Website Loading Issues
**Is your feature request related to a problem? Please describe.**
Based on the report from [PageSpeed Insights](https://pagespeed.web.dev/analysis/https-www-now-u-com/k8f721i962?form_factor=desktop), the now-u website is currently experiencing slow loading issues. (could refer to the discussion [here](https://docs.google.com/document/d/16Y7pB6eulRnPpc4Xjm4XyxhzYcqwEUGOadVQ_FQNVw0/edit?pli=1&disco=AAABVKhPo4s) to gain more backgrounds)

**Describe the solution you'd like**
We'd like to investigate the root causes and make improvements, aiming to reach a score of 90+ on PageSpeed for every website page.

### PR DESCRIPTION
**Pull request by clementinelove**
Closes #52 

The Website performance is mainly impacted by large, unoptimized images.
This is mainly due to images don't have sizes specified, which causes Next.js's `next/image` component unable to do do optimizations based on images' dimensions.

There are also some code refactors around app download badge components and footer design.

### CODE REVIEW

**Comment by clementinelove** [comment]
@JElgar Honestly I feel the website preview is pretty snappy, but the PageInsight still give us very low score sometimes. Likely due to our API calls... 
However, since Vercel also have a [speed insight tool](https://vercel.com/docs/speed-insights?utm_campaign=no-campaign#metrics?utm_source=next-site&utm_medium=learnpages&utm_campaign=no-campaign), can you help me check the performance on that tool?

**Comment by JElgar** [comment]
Thank you for this! Looks awesome. One image that is noticably less clear though is the one on the landing page (staging is on the right and this cr preview is on the right). Do you think we can bump that?

It looks like the logos have increased in size but I kinda like that so we can probably keep it. However it does look like the outline is gone, is that intentional?
 
image

**Comment by JElgar** [comment]
Ok just had a bit of a wider look, I think we might need to bump the quality of all the infographic images. I don't think by much but at least on the mobile view they all have a touch of noticeable blur.

**Comment by clementinelove** [comment]
> Ok just had a bit of a wider look, I think we might need to bump the quality of all the infographic images. I don't think by much but at least on the mobile view they all have a touch of noticeable blur.

You are right, I've made some changes to make it look less blurry. Have a look at the latest preview plz!

**Pull request merged**
